---
- name: Getting Devices
  hosts: linux_devices
  gather_facts: yes
  tasks:
    ### updateing packages
#    - name: System update
 #     ansible.builtin.dnf:
  #      name: "*"
   #     state: "latest"
   
    - name: Creating user groups
      ansible.builtin.group:
        name: "{{ item }}"
      loop:
        - "admin"
        - "eng"
        - "hr"
  
      ### config groups (admin, engineering, hr)
  

      ### configure users for preset groups 
