---
- name: Getting Devices
  hosts: linux_devices
  gather_facts: yes
  tasks:
    ### updateing packages
#    - name: System update
 #     ansible.builtin.dnf:
  #      name: "*"
   #     state: "latest"
   
    - name: Creating user groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
      loop:
        - name: admin
          gid: 12345
        - name: eng
          gid: 23456
        - name: hr
          gid: 34567
  
    ### creates a single admin account for management ###
    - name: Create admin account
      ansible.builtin.user:
        password: $6$.tsHTsq9F7hTYiW2$pJa8uufg0P.QWkhzcPdjF1wqSWBho5nNYCwMXev.A4OnAJGiCMXM4v9ng3T4DwzwWf5ZavsRtLUhy6Zxp266B.           
        shell: /bin/bash
        uid: 2020
        create_home: true
        name: admin2
        append: true
        groups: wheel

      ### configure users for preset groups 

