--
- name: Getting Devices
  hosts: linux_devices
  gather_facts: yes
  tasks:
    ### updateing packages
#    - name: System update
 #     ansible.builtin.dnf:
  #      name: "*"
   #     state: "latest"
   
    - name: Creating user groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
      loop:
        - name: admin
          gid: 12345
        - name: eng
          gid: 23456
        - name: hr
          gid: 34567
  
      ### config groups (admin, engineering, hr)
      #- name: Create admin account
      # ansible.builtin.user:
         

      ### configure users for preset groups 
